<a href="https://colab.research.google.com/github/Raghad770/UTK/blob/main/Tahluf_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part-2 Coding Exam

## Outlines

- Creating Arrays
- Initial Placeholders
- Array Inspection
- Array Mathematics
- Array Manipulation
- DataFrame
- Selecting, Boolean Indexing & Setting
- Dropping
- Retrieving DataFrame Information

## Notes
- All problems MUST be solved
- Read the problems well, before you start solving.
- The solution MUST pass all the test cases
- Feel free to add more cells to develope the program, BUT make sure you gather them in ONE adequately working code cell.  
- You also should create all the numpy input arrays first.

### This exam consists of 34 mini-questions based on what you toke in session and also on some simple research you should make online.

#### Good Luck

# Pandas and Numpy

## Problem 1

#### Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
#### Expected Output:
#### Array1: [ 0 10 20 40 60]
#### Array2: [0, 40]
#### Compare each element of array1 and array2
#### Output: [ True False False True False]

In [ ]:
import numpy as np

In [ ]:
### Write Your Code Here ###
Arr1=[ 0,10, 20, 40, 60]
Arr2=[0, 40]
out_arr=[]
flag='false'
for i in range(max(len(Arr1),len(Arr2))):
  for j in range(min(len(Arr1),len(Arr2))):
    if(Arr1[i]==Arr2[j]):
      flag='true'
      break
    else:
      flag='false'
  if(flag=='true'):
      out_arr.append('True')       
  else:
       out_arr.append('False')  
   
print(out_arr)
  

['True', 'False', 'False', 'True', 'False']


## Problem 2
#### Write a NumPy program to get the unique elements of an array
#### Expected Output:
#### Original array:
#### [10 10 20 20 30 30]
#### Unique elements of the above array:
#### [10 20 30]
#### Original array:
#### [[1 1]
#### [2 3]]
#### Unique elements of the above array:
#### [1 2 3]

In [ ]:
### Write Your Code Here ###
arr1=np.array([[1, 1]
,[2, 3]])
arr2=np.array([10, 10, 20, 20, 30, 30])
arr1=arr1.flatten()
arr2=arr2.flatten()

def unique(list1):
  print("original array")
  print(list1)
  # initialize a null list
  unique_list = []   
  # traverse for all elements
  for x in list1:
  # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
  print("Unique elements of the above array:")         
  print(unique_list)

unique(arr1)
unique(arr2)

#print(arr2)


original array
[1 1 2 3]
Unique elements of the above array:
[1, 2, 3]
original array
[10 10 20 20 30 30]
Unique elements of the above array:
[10, 20, 30]


## Problem 3
#### Write a NumPy program to sort an along the first, last axis of an array.
#### Sample array: [[2,5],[4,4]]
#### Expected Output:
#### Original array:
#### [[4 6]
#### [2 1]]
#### Sort along the first axis:
#### [[2 1]
#### [4 6]]
#### Sort along the last axis:
#### [[1 2]
#### [4 6]]

In [ ]:
### Write Your Code Here ###
arr3 = np.array([[2,5],[4,4]])
print("Original array: ")
print(arr3)
print("Sort along the first axis: ")
x = np.sort(arr3, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[2 5]
 [4 4]]
Sort along the first axis: 
[[2 4]
 [4 5]]
Sort along the last axis: 
[[2 4]
 [4 5]]


## Problem 4
#### Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
#### Sample Output:
#### Original array:
#### [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
#### [4,1,7,3]

In [ ]:
### Write Your Code Here ###
arr4=np.array([10, 20, 20 ,20 ,20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
item=[0,10,20,30]
list=[]
def occurenc(org_arr,items):
  print("original array:")
  print(org_arr)
  for i in item:
    count=0
    for j in arr4:
      if i==j:
        count=count+1
    list.append(count)
  print(list)

occurenc(arr4,item)


original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
[4, 1, 7, 3]


## Problem 5
#### Write a NumPy program to remove nan values from a given array.
#### Sample Output:
#### Original array:
#### [200. 300. nan nan nan 700.]
#### After removing nan values:
#### [200. 300. 700.]

In [ ]:
### Write Your Code Here ###
# we can use np.nan
arr5=np.array([200., 300. ,np.nan ,np.nan ,np.nan, 700.])
print('original array')
print(arr5)
# remove nan values using numpy.isnan()
# and numpy.logical_not
b = arr5[np.logical_not(np.isnan(arr5))]
print('after removing nan values')
print(b)



original array
[200. 300.  nan  nan  nan 700.]
after removing nan values
[200. 300. 700.]


## Problem 6
#### Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
#### Sample Output:
#### 50th percentile (median):
#### 3.0
#### 40th percentile:
#### 2.6
#### 90th percentile:
#### 4.6

In [ ]:
### Write Your Code Here ###

## Problem 7
#### Write a NumPy program to find indices of elements equal to zero in a NumPy array.
#### Sample Output:
#### Original array:
#### [1 0 2 0 3 0 4 5 6 7 8]
#### Indices of elements equal to zero of the said array:
#### [1 3 5]

In [ ]:
### Write Your Program Here ###
arr6=np.array([1 ,0 ,2 ,0 ,3 ,0 ,4 ,5 ,6 ,7 ,8])
list=[]
for i in range(len(arr6)):
  if arr6[i]==0:
    list.append(i)
print(list)

[1, 3, 5]


## Problem 8

#### Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
#### Sample Output:
#### Original array:
#### [-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
#### Round elements of the array to the nearest integer:
#### [1. 2. 2. 0. 2. 2. 2.]

In [ ]:
### Write Your Program Here ###
org_arr=np.array([-0.7,-1.5, -1.7, 0.3, 1.5, 1.8, 2. ])
print("original array")
print([-0.7,-1.5, -1.7, 0.3, 1.5, 1.8, 2. ])
list=[]

def rounding(arr):
  for x in arr:
    if (abs(x) - abs(int(x))) < 0.5:
        x= abs(int(x))
    else:
        x= abs(int(x)) + 1
    list.append(x)

rounding(org_arr)    
print("Round elements of the array to the nearest integer:")
print(list)

original array
[-0.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0]
Round elements of the array to the nearest integer:
[1, 2, 2, 0, 2, 2, 2]


## Problem 9
#### Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
#### Sample output:
#### Original array:
#### [1 3 5 7 0]
#### Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
#### [ 0 0 2 2 2 -7 200]
#### Note:  difference between neighboring elements means: $out[i] = a[i+1] - a[i]$

In [ ]:
### Write Your Code Here ###
arr=np.array([1 ,3 ,5 ,7 ,0])
print("original array")
print(arr)
arr2=[]
arr2.append(0)
arr2.append(0)
for i in range(0,len(arr)-1):
  arr2.append(arr[i+1]-arr[i])
arr2.append(200)  
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:")
print(arr2)

original array
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[0, 0, 2, 2, 2, -7, 200]


## Problem 10
#### Write a NumPy program to get the indices of the sorted elements of a given array.
#### Expected Output:
#### Original array:
#### [1023 5202 6230 1671 1682 5241 4532]
#### Indices of the sorted elements of a given array:
#### [0 3 4 6 1 5 2]

In [ ]:
### Write Your Code Here ###
arr=np.array([1023 ,5202, 6230, 1671 ,1682 ,5241 ,4532])
list=[0,1,2,3,4,5,6]

print("original array")
print(arr)

for i in range(len(arr)):
  idxj=0
  idxi=0
  for j in range(i+1,len(arr)):
    if arr[j]<arr[i]:
      x=arr[j]
      arr[j]=arr[i]
      arr[i]=x
      y=list[j]
      list[j]=list[i]
      list[i]=y
      
print("Indices of the sorted elements of a given array:")  
print(list)



original array
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0, 3, 4, 6, 1, 5, 2]


## Problem 11
#### Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
#### Sample output:
#### Original array:
#### [ 70 50 20 30 -11 60 50 40]
#### After partitioning on 4 the position:
#### [-11 30 20 40 50 50 60 70]

In [ ]:
### Write Your Code Here ###
import numpy as np
arr=np.array([ 70, 50, 20, 30, -11, 60, 50 ,40])
#arr=np.array([ 70, -85, 20, 30, -11, 60, -90 ,40]) for testing
print("original array")
print(arr)
part=4
smallList=[]
greatList=[]
list=[]
def partitioning(part,org_arr):
  for i in range(len(arr)):
    if arr[i]<arr[part]:
      smallList.append(arr[i]) 

    elif arr[i]>arr[part]:
      greatList.append(arr[i])
     
  smallList.append(arr[part])
  r1 = np.ediff1d(list, to_begin=smallList, to_end=greatList)  
  print("After partitioning on 4 the position:")
  print(r1) 
# print(smallList)
#print(greatList) 
partitioning(part,arr)



original array
[ 70  50  20  30 -11  60  50  40]
After partitioning on 4 the position:
[-11.  70.  50.  20.  30.  60.  50.  40.]


## Problem 12
#### Compute the euclidean distance between two arrays a and b.

#### Input:
#### [1,2,3,4,5]
#### [4,5,6,7,8]
#### Euclidean distance is: 6.7082

In [ ]:
### Write You Program Here ###
from numpy.linalg import norm
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

print("Euclidean distance is:",norm(arr1-arr2))

#we can use the mathematical formula
dist = np.sqrt(np.sum(np.square(arr1-arr2)))
print("Euclidean distance is:",dist)

Euclidean distance is: 6.708203932499369
Euclidean distance is: 6.708203932499369


## Problem 13
#### Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

#### Input:

#### array([1, 3, 7, 1, 2, 6, 0, 1])

#### Desired Output:

#### array( [2, 5])
#### where, 2 and 5 are the positions of peak values 7 and 6.

In [ ]:
### Write You Program Here ###
arr=np.array([1, 3, 7, 1, 2, 6, 0, 1])
#arr=np.array([1, 3, 7, 1, 9, 6, 8, 1]) for testing
list=[]
for i in range(1,len(arr)-1):
  if arr[i]>arr[i-1] and arr[i]>arr[i+1]:
    list.append(i)
print(list)

[2, 5]


## Problem 14
#### Find the index of nth repetition of number i .
#### Inputs
#### array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
#### n = 5 (from user)
#### i = 1 (from user)
#### Output
#### 8

In [ ]:
### Write Your Code Here ###
arr=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n=5
i=1
def repetition_index(n,i,arr):
  counter=0
  for j in range(len(arr)):
    if counter<n:
      if arr[j]==i:
        counter=counter+1
        if  counter==n:
          idx=j
          print(idx)
    if j==len(arr)-1 and counter !=n:
      print("there is no nth repetion for this number")   # for handling more cases


repetition_index(n,i,arr)



8


## Problem 15
### In order to solve this set of questions you will use the dataset in the relative directory ./Datasets/tmdb_5000_movies.csv


**Open Your CSV file and print the first 10 rows in a good format**

In [19]:
### Open Your CSV file and print the first 10 rows in a good format ###
# importing the important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
%matplotlib inline

# Load data 
file_path = "/tmdb_5000_movies.csv"
df = pd.read_csv(file_path)
#and print out (first 10 rows).
df.head(10)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            homepage      id  \
0                        http://www.avatarmovie.com/   19995   
1       http://disney.go.com/disneypictures/pirates/     285   
2        http://www.sonypictures.com/movies/spectre/  206647   
3                 http://www.thedarkknightrises.com/   49026   
4               http://movies.disney.com/john-carter   49529   
5    http://www.sonypictures.com/movies/spider-man3/     559   
6       http://disney.go.com/disneypictures/tangled/   38757   
7  http://marvel.com/movies/movie/193/avengers_ag...   99861   
8  http://harrypotter.warnerbros.com/harrypottera...     767   
9       http://www.batmanvsupermandawnofjustice.com/  209112   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   
5  [{"id": 851, "name": "dual identity"}, {"id": ...                en   
6  [{"id": 1562, "name": "hostage"}, {"id": 2343,...                en   
7  [{"id": 8828, "name": "marvel comic"}, {"id": ...                en   
8  [{"id": 616, "name": "witch"}, {"id": 2343, "n...                en   
9  [{"id": 849, "name": "dc comics"}, {"id": 7002...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   
5                              Spider-Man 3   
6                                   Tangled   
7                   Avengers: Age of Ultron   
8    Harry Potter and the Half-Blood Prince   
9        Batman v Superman: Dawn of Justice   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   
5  The seemingly invincible Spider-Man goes up ag...  115.699814   
6  When the kingdom's most wanted-and most charmi...   48.681969   
7  When Tony Stark tries to jumpstart a dormant p...  134.279229   
8  As Harry begins his sixth year at Hogwarts, he...   98.885637   
9  Fearing the actions of a god-like Super Hero l...  155.790452   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   
5  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
6  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
7  [{"name": "Marvel Studios", "i

**Check if any NANs in your dataset and fill them with a good filer**


In [45]:
#to show all nans in dataset
#print(df.isnull())
#to tell you if there is any nan vlaues any dataset or no
print(df.isnull().values.any())
# a list of all nans summations of each column
print(df.isnull().sum())

True
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64


In [63]:
#the shape of dataframe before removing colums with num of nan values >50% 
print(df.shape)
#make a copy
df_clean = df.copy()
#show the first 5 colums which have largest values of nan values
print(df_clean.isnull().sum().nlargest(5))

df_shape=df_clean.shape

#home page has num of nan values more than 50%
print("precentage of num of nan val in homepage column",df['homepage'].isnull().sum()*100.0/df_shape[0])

column_with_nan = df_clean.columns[df.isnull().any()]

# 1--so i will remove columns with num of nan values more than 50%
for column in column_with_nan:
   if df[column].isnull().sum()*100.0/df_shape[0] >= 50:
             df_clean.drop(column,1, inplace=True) 
#the shape of dataframe after removing colums with num of nan values >50% 
print(df_clean.shape)


(4803, 20)
homepage        3091
tagline          844
overview           3
runtime            2
release_date       1
dtype: int64
precentage of num of nan val in homepage column 64.35561107641058
(4803, 19)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only


In [64]:
print(df_clean.isnull().sum().nlargest(5))
index_with_nan_tagline = df_clean['tagline'].index[df_clean.isnull().any(axis=1)]
#drop rows with nan values
df_clean.drop(index_with_nan_tagline,0, inplace=True)
print(df_clean.shape)

tagline         844
overview          3
runtime           2
release_date      1
budget            0
dtype: int64
(3959, 19)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.


In [65]:
#show if there is any nan values in other columns
print(df_clean.isnull().sum().nlargest(5))
print(df_clean.shape) # there is no any nan values

#check if there are dublicated records
df_clean.duplicated()
df_clean.duplicated().sum() #there is no any dublicated records


budget               0
genres               0
id                   0
keywords             0
original_language    0
dtype: int64
(3959, 19)


0

**Discover the types of each columns and modify them if needed**

In [66]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3959 entries, 0 to 4801
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                3959 non-null   int64  
 1   genres                3959 non-null   object 
 2   id                    3959 non-null   int64  
 3   keywords              3959 non-null   object 
 4   original_language     3959 non-null   object 
 5   original_title        3959 non-null   object 
 6   overview              3959 non-null   object 
 7   popularity            3959 non-null   float64
 8   production_companies  3959 non-null   object 
 9   production_countries  3959 non-null   object 
 10  release_date          3959 non-null   object 
 11  revenue               3959 non-null   int64  
 12  runtime               3959 non-null   float64
 13  spoken_languages      3959 non-null   object 
 14  status                3959 non-null   object 
 15  tagline              

In [67]:
# check for number of the unique values for each column
col = list(df_clean.columns.values)
for i in col:
    noUniq = df_clean[i].nunique()    
    print( "number of unique values in {} is :".format(i) ,noUniq)
print("_______________________________________________________________________")    
# check for the unique values in some columns
col = list(df_clean.columns.values)
for i in col:
    if i in ['original_language', 'status']:
        unique = df[i].unique()
        print( "number of unique value in {} is :".format(i) , unique )
#unique values in original_language is : 37
#number of unique values in status is : 3

number of unique values in budget is : 393
number of unique values in genres is : 1068
number of unique values in id is : 3959
number of unique values in keywords is : 3675
number of unique values in original_language is : 29
number of unique values in original_title is : 3957
number of unique values in overview is : 3959
number of unique values in popularity is : 3958
number of unique values in production_companies is : 3163
number of unique values in production_countries is : 381
number of unique values in release_date is : 2886
number of unique values in revenue is : 3030
number of unique values in runtime is : 141
number of unique values in spoken_languages is : 469
number of unique values in status is : 3
number of unique values in tagline is : 3944
number of unique values in title is : 3956
number of unique values in vote_average is : 65
number of unique values in vote_count is : 1587
_______________________________________________________________________
number of unique value i

In [71]:
#extract 'original_language','status' columns
cols = ['original_language','status']
df_cols = df_clean[cols]

#convert all categorical columns to numeric
df_clean[cols] =df_cols.apply(lambda x: pd.factorize(x)[0])
#print(df_clean)
print(df_cols)

      original_language  status
0                     0       0
1                     0       0
2                     0       0
3                     0       0
4                     0       0
...                 ...     ...
4795                  0       0
4796                  0       0
4798                  6       0
4799                  0       0
4801                  0       0

[3959 rows x 2 columns]


In [ ]:
#change the datatype of "id" column to be strings
df_clean['id'] = df_clean['id'].astype(str)

#the Change the datatype of 'release_date' column into be in Datetime
df_clean["release_date"] = pd.to_datetime(df_clean['release_date']).dt.date.astype('datetime64[ns]')

#check outcome
print (df_clean["release_date"].dtypes)
df_clean.head()

In [ ]:
### Give a very simple statistical analsys for the numerical columns ###



In [ ]:
### Calculate the mean rate for [1999, 1980, 2004, 2017] the movies grouped by years ###

### Ex: Average Movies Rate at 2009 is 6.065587 ###



In [ ]:
### Rearange the dataframe based on revenue - budget values ###



In [ ]:
### Allocate the year with the largest movies released in ['Action', 'Romance'] ###



In [ ]:
### Find the movies with top 5 revenue - budget value ###



In [ ]:
### Find the year with the highest number of movies release ###



In [ ]:
### Find the top 2 countries with the highest production movies number ###



In [ ]:
### Find the top 1 company with the highest production movies number ###



In [ ]:
### Is there any relation between the runtime and average vote value ### **



In [ ]:
### Find the top 5 movies with the highest rate, and find if there anything common between them. ###



In [ ]:
### Find the most unsuccessful movie along time in terms of revenue - budget ###



In [ ]:
### Rearange the dataframe based on vote_average column values ###



In [ ]:
### Rearange the dataframe based on runtime column values ###



In [ ]:
### Find the top 5 successful years for the USA cinema based on the total income devided by number of movies  ###



In [ ]:
### Find the most succesfull movie in [USA, UK] ###



In [ ]:
### In your opinion what is the highest variable that affects the revenue value (high coloration) ### PONUS



#  <span style="color:brown">Problem 16

## <span style="color:blue">Problem statment

The content, tone, and format of job bulletins can influence the quality of the applicant pool. Overly-specific job requirements may discourage diversity. The Los Angeles Mayor’s Office wants to reimagine the city’s job bulletins by using text analysis to identify needed improvements, in order to achive this use the daatset in the relative diretcotry ./Datasets/la_jobs.csv, and this is the decomentation for the useful columns you should use:

- FILE_NAME: The bulletins file name.
- JOB_CLASS_TITLE: Job title.
- JOB_CLASS_NO: Job number.
- JOB_DUTIES: The duties of this job.
- EDUCATION_YEARS: Number of education yeras needed to apply for this job.
- SCHOOL_TYPE: The type of school you need to study in.
- EDUCATION_MAJOR: The eductaion major you study in this school.
- EXPERIENCE_LENGTH: The number of experience years needed to apply for this job .
- FULL_TIME_PART_TIME: If the job is full time or part time or both.
- EXP_JOB_CLASS_TITLE: The title of the job you must have experience in before applying in this job.
- COURSE_COUNT: Number of courses neede to apply for this job.
- COURSE_LENGTH: The course length in years or months.
- COURSE_SUBJECT: The course subject tha is needed to be accepted in this job.
- DRIVERS_LICENSE_REQ: Is driver license required or not for this job.
- EXAM_TYPE: Type of exams neededin the hiring process.
- ENTRY_SALARY: Salary range in this job.
- OPEN_DATE: Date at it the job bulliten got open.
- REQUIREMENT_SET_TEXT: The requirments set need for this job in points.

    

#### The goal is to answer the following questions
 

### <span style="color:brown">Q1:

A non-experienced job seeker wants to know what is the best job for him?

In [ ]:
### Write your answer here ###

### <span style="color:brown">Q2:

A concerned parents contacts you to tell them if there is a spicific school type that would guaranteed for their child a good future if you can tell, and which is it ?

In [ ]:
### Write your answer here ###

### <span style="color:brown">Q3:

What the best time in the year to be ready for a job applying in any experience level?

In [ ]:
### Write your answer here ###

### <span style="color:brown">Q4:

Is experience more important than educational level?

In [ ]:
### Write your answer here ###

### <span style="color:brown">Q5:

Which fresh grade job that will guarantee many job offers in the future for him?

In [ ]:
### Write your answer here ###

### <span style="color:brown">Q6:

"The City of Los Angeles does not discriminate on the basis of race, religion, national origin, sex, age, marital status, sexual orientation, gender identity, gender expression, disability, creed, color, ancestry, medical condition (cancer), or Acquired Immune Deficiency Syndrome.

AN EQUAL EMPLOYMENT OPPORTUNITY EMPLOYER 
"

The above statment is qouted from one of the job descriptions.

Based on the jobs requirments column above do you think that LA governate may bais a little for men over women or the applicant marital status for example may effect his chance to gain the job?

In [ ]:
### Write your answer here ###

#  <span style="color:brown">Pythone Implementation

## Problem 17

### <span style="color:Blue">Song Recommender</span>

#### <a id='seq_1'></a> Build a simple program that recommend songs to the user , based on his feelings and current mood, the songs recommendation rely on five categories:
- Cheering
- Sad
- In Love
- Motivated
- Calm

#### Each song has a total score of 5 for each category, so you should ask the user for his percentage for each category, with a simple restriction that the category score must not exceed 5.
#### Then you should find the closest song to his feelings based on a simple difference calculation equation shown below:
$ \sqrt{(I_1 - R_1)^2 + (I_2 - R_2)^2 + (I_3 - R_3)^2 + (I_4 - R_4)^2} $
##### As $ I_i $ is the input feeling value number i, and $ R_i $ is the refrence feeling value number i, as  $ i <= 4 $
##### you will find below in the coding cell a nested dictionary with all the songs and its scores for each category, and also atatched in each dictionary a link to the song in youtube.

#### Output Discription:
|Case|Output|
|--|--|
|Standard|Song Name<br>Link to the video in youtube|

#### Notes
- The input categories order is as [above](#seq_1)
- Make sure the score for each category is 5 at max.
- All inputs must be casted to float.
- The songs are listed in a nested dictionary with values of each category down below.

In [ ]:
### Write your answer here ###

## Good Luck